//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET_QLKS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NET_QLKS1Entities : DbContext
    {
        public NET_QLKS1Entities()
            : base("name=NET_QLKS1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HOADON> CT_HOADON { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACH> KHACHes { get; set; }
        public virtual DbSet<LOAIPHONG> LOAIPHONGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHOMQUYEN> NHOMQUYENs { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual DbSet<PHIEUDATPHONG> PHIEUDATPHONGs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
    
        [DbFunction("NET_QLKS1Entities", "FUNC_DVPH")]
        public virtual IQueryable<FUNC_DVPH_Result> FUNC_DVPH(Nullable<int> mAHD)
        {
            var mAHDParameter = mAHD.HasValue ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_DVPH_Result>("[NET_QLKS1Entities].[FUNC_DVPH](@MAHD)", mAHDParameter);
        }
    
        [DbFunction("NET_QLKS1Entities", "FUNC_FINDHDY")]
        public virtual IQueryable<FUNC_FINDHDY_Result> FUNC_FINDHDY(string tENPHONG)
        {
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_FINDHDY_Result>("[NET_QLKS1Entities].[FUNC_FINDHDY](@TENPHONG)", tENPHONGParameter);
        }
    
        [DbFunction("NET_QLKS1Entities", "FUNC_FINDHDYED")]
        public virtual IQueryable<FUNC_FINDHDYED_Result> FUNC_FINDHDYED(Nullable<int> mAHD)
        {
            var mAHDParameter = mAHD.HasValue ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_FINDHDYED_Result>("[NET_QLKS1Entities].[FUNC_FINDHDYED](@MAHD)", mAHDParameter);
        }
    
        [DbFunction("NET_QLKS1Entities", "FUNC_FINDKH")]
        public virtual IQueryable<FUNC_FINDKH_Result> FUNC_FINDKH(string cCCD)
        {
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_FINDKH_Result>("[NET_QLKS1Entities].[FUNC_FINDKH](@CCCD)", cCCDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PROC_DANGNHAP(string tENDK, string mATKHAU)
        {
            var tENDKParameter = tENDK != null ?
                new ObjectParameter("TENDK", tENDK) :
                new ObjectParameter("TENDK", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PROC_DANGNHAP", tENDKParameter, mATKHAUParameter);
        }
    
        public virtual ObjectResult<PROC_FINDDV_Result> PROC_FINDDV(string tENDV)
        {
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_FINDDV_Result>("PROC_FINDDV", tENDVParameter);
        }
    
        public virtual ObjectResult<PROC_FINDLOAI_Result> PROC_FINDLOAI(string tENLOAI)
        {
            var tENLOAIParameter = tENLOAI != null ?
                new ObjectParameter("TENLOAI", tENLOAI) :
                new ObjectParameter("TENLOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_FINDLOAI_Result>("PROC_FINDLOAI", tENLOAIParameter);
        }
    
        public virtual ObjectResult<PROC_FINDNV_Result> PROC_FINDNV(string tENNV)
        {
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_FINDNV_Result>("PROC_FINDNV", tENNVParameter);
        }
    
        public virtual ObjectResult<PROC_FINDPDP_Result> PROC_FINDPDP(Nullable<int> mAPDP)
        {
            var mAPDPParameter = mAPDP.HasValue ?
                new ObjectParameter("MAPDP", mAPDP) :
                new ObjectParameter("MAPDP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_FINDPDP_Result>("PROC_FINDPDP", mAPDPParameter);
        }
    
        public virtual ObjectResult<PROC_FINDPHONG_Result> PROC_FINDPHONG(string tENPHONG)
        {
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_FINDPHONG_Result>("PROC_FINDPHONG", tENPHONGParameter);
        }
    
        public virtual int PROC_THEMDV(string tENDV, Nullable<double> gIADV)
        {
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            var gIADVParameter = gIADV.HasValue ?
                new ObjectParameter("GIADV", gIADV) :
                new ObjectParameter("GIADV", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_THEMDV", tENDVParameter, gIADVParameter);
        }
    
        public virtual int PROC_THEMLOAI(string tENLOAI, Nullable<int> sUCCHUA)
        {
            var tENLOAIParameter = tENLOAI != null ?
                new ObjectParameter("TENLOAI", tENLOAI) :
                new ObjectParameter("TENLOAI", typeof(string));
    
            var sUCCHUAParameter = sUCCHUA.HasValue ?
                new ObjectParameter("SUCCHUA", sUCCHUA) :
                new ObjectParameter("SUCCHUA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_THEMLOAI", tENLOAIParameter, sUCCHUAParameter);
        }
    
        public virtual int PROC_UPDICHVU(Nullable<int> mADV, string tENDV, Nullable<double> gIADV)
        {
            var mADVParameter = mADV.HasValue ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(int));
    
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            var gIADVParameter = gIADV.HasValue ?
                new ObjectParameter("GIADV", gIADV) :
                new ObjectParameter("GIADV", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDICHVU", mADVParameter, tENDVParameter, gIADVParameter);
        }
    
        public virtual int PROC_UPLOAIPHONG(Nullable<int> mALOAI, string tENLOAI, Nullable<int> sUCCHUA)
        {
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            var tENLOAIParameter = tENLOAI != null ?
                new ObjectParameter("TENLOAI", tENLOAI) :
                new ObjectParameter("TENLOAI", typeof(string));
    
            var sUCCHUAParameter = sUCCHUA.HasValue ?
                new ObjectParameter("SUCCHUA", sUCCHUA) :
                new ObjectParameter("SUCCHUA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPLOAIPHONG", mALOAIParameter, tENLOAIParameter, sUCCHUAParameter);
        }
    
        public virtual int PROC_UPSTATE_PH(string tENPHONG, string tRANGTHAI)
        {
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI != null ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPSTATE_PH", tENPHONGParameter, tRANGTHAIParameter);
        }
    }
}
